//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmCategories
    {
        public int id { get; set; }
        public Nullable<int> id_film { get; set; }
        public Nullable<int> id_category { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Films Films { get; set; }
    }
}
