//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MWVMLib;

namespace DatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSession : ViewModelBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieSession()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int id { get; set; }

        private Nullable<int> _idFilm;

        public Nullable<int> id_film
        {
            get { return _idFilm; }
            set { _idFilm = value;
                OnPropertyChanged(nameof(id_film));
            }
        }

        //public Nullable<int> id_film { get; set; }
        //public Nullable<int> id_cinema { get; set; }

        private int _idCinema;

        public int id_cinema
        {
            get { return _idCinema; }
            set { _idCinema = value;
                OnPropertyChanged(nameof(id_cinema));
            }
        }

        //public Nullable<int> id_hall { get; set; }

        private int _idHall;

        public int id_hall
        {
            get { return _idHall; }
            set { _idHall = value;
                OnPropertyChanged(nameof(id_hall));
            }
        }

        //public Nullable<System.DateTime> date { get; set; }

        private Nullable<System.DateTime> _date;

        public Nullable<System.DateTime> date
        {
            get { return _date; }
            set { _date = value;
                OnPropertyChanged(nameof(date));
            }
        }


        public virtual Cinemas Cinemas { get; set; }
        public virtual Films Films { get; set; }
        public virtual Hall Hall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
